'use client'
import { useLanguage } from '@/lib/i18n'
type Day = { day: string; views: number; visitors: number }
export default function AdminTraffic({ days, pages }: { days: Day[]; pages: { path: string; views: number }[] }) {
 const { lang } = useLanguage(); const de = lang === 'de'
 const today = days.at(-1)!
 const max = Math.max(1, ...days.map(d => d.views))
 return <section className="panel mb-8 p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">{de ? 'Website-Traffic' : 'Website traffic'}</h2><button onClick={() => window.location.reload()} className="text-sm text-emerald-300">{de ? 'Aktualisieren' : 'Refresh'}</button></div>
 <div className="my-6 grid gap-4 sm:grid-cols-3">{[[de ? 'Aufrufe heute' : 'Page views today', today.views], [de ? 'Besucher heute (geschätzt)' : 'Visitors today (estimated)', today.visitors], [de ? 'Aufrufe · 30 Tage' : 'Page views · 30 days', days.reduce((sum,d) => sum+d.views,0)]].map(([label,value]) => <div key={label} className="rounded-xl bg-slate-950/60 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>)}</div>
 <div className="flex h-28 items-end gap-1" role="img" aria-label={de ? 'Tägliche Seitenaufrufe der letzten 30 Tage; genaue Werte in der Tabelle.' : 'Daily page views over 30 days; exact values in the table.'}>{days.map(d => <div key={d.day} title={`${d.day}: ${d.views}`} className="flex-1 rounded-t bg-emerald-400/70" style={{height:`${Math.max(2, d.views/max*100)}%`}} />)}</div>
 <p className="mt-4 text-xs leading-relaxed text-slate-400">{de ? 'Tage in Europe/Berlin. Besucher sind tägliche Schätzungen aus kurzlebigen, täglich wechselnden Kennungen, keine eindeutigen Personen. Keine Tracking-Cookies. Admin-Aufrufe, bekannte Bots sowie Do Not Track/GPC werden ausgeschlossen. Browser-Blocker und gemeinsame Netzwerke beeinflussen die Zahlen. Die Erfassung beginnt mit dieser Veröffentlichung.' : 'Days use Europe/Berlin. Visitors are daily estimates from short-lived identifiers that change each day, not distinct people. No tracking cookies. Admin visits, known bots and Do Not Track/GPC are excluded. Browser blockers and shared networks affect counts. Collection starts with this release.'}</p>
 <div className="mt-6 grid gap-6 md:grid-cols-2"><details><summary className="cursor-pointer text-sm text-emerald-300">{de ? 'Tagesübersicht' : 'Daily breakdown'}</summary><table className="mt-3 w-full text-sm"><thead><tr className="text-left text-slate-400"><th>{de ? 'Tag' : 'Day'}</th><th>{de ? 'Aufrufe' : 'Views'}</th><th>{de ? 'Besucher ≈' : 'Visitors ≈'}</th></tr></thead><tbody>{[...days].reverse().map(d=><tr key={d.day} className="border-t border-white/5"><td className="py-2">{d.day}</td><td>{d.views}</td><td>{d.visitors}</td></tr>)}</tbody></table></details><div><h3 className="text-sm text-slate-300">{de ? 'Beliebte Seiten · 30 Tage' : 'Popular pages · 30 days'}</h3>{!pages.length && <p className="mt-3 text-sm text-slate-500">{de ? 'Noch keine Aufrufe erfasst.' : 'No page views recorded yet.'}</p>}{pages.map(p => <div key={p.path} className="flex justify-between border-b border-white/5 py-2 text-sm"><span>{p.path}</span><span>{p.views}</span></div>)}</div></div></section>
}
